In [2]:
!pip install pandas upgrade nbformat nbconvert jupyter

In [3]:
!pip install --upgrade nbformat nbconvert jupyter

In [1]:
import pandas as pd

In [38]:
df = pd.read_csv(r'C:\Users\gerem\Desktop\datathon-7mlet-grupo-77\data\kaggle\bank-additional-full.csv', sep=';')

In [39]:
df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [40]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y'],
      dtype='str')

In [41]:
column_translation = {
    "age": "idade",
    "job": "profissao",
    "marital": "estado_civil",
    "education": "escolaridade",
    "default": "inadimplencia",
    "housing": "emprestimo_habitacional",
    "loan": "emprestimo_pessoal",
    "contact": "tipo_contato",
    "month": "mes_contato",
    "day_of_week": "dia_semana",
    "duration": "duracao_contato",
    "campaign": "numero_contatos_campanha",
    "pdays": "dias_desde_ultimo_contato",
    "previous": "numero_contatos_anteriores",
    "poutcome": "resultado_campanha_anterior",
    "emp.var.rate": "taxa_variacao_emprego",
    "cons.price.idx": "indice_preco_consumidor",
    "cons.conf.idx": "indice_confianca_consumidor",
    "euribor3m": "taxa_euribor_3_meses",
    "nr.employed": "numero_empregados",
    "y": "conversao"
}

In [42]:
df = df.rename(columns=column_translation)

In [43]:
df = df.drop(columns=['duracao_contato', 'inadimplencia'])

In [44]:
df.head()

,idade,profissao,estado_civil,escolaridade,emprestimo_habitacional,emprestimo_pessoal,tipo_contato,mes_contato,dia_semana,numero_contatos_campanha,dias_desde_ultimo_contato,numero_contatos_anteriores,resultado_campanha_anterior,taxa_variacao_emprego,indice_preco_consumidor,indice_confianca_consumidor,taxa_euribor_3_meses,numero_empregados,conversao
0,56,housemaid,married,basic.4y,no,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,no,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,yes,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,yes,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [45]:
(df.isna().sum() / df.shape[0] * 100).sort_values(ascending = False)

idade                          0.0
profissao                      0.0
estado_civil                   0.0
escolaridade                   0.0
emprestimo_habitacional        0.0
emprestimo_pessoal             0.0
tipo_contato                   0.0
mes_contato                    0.0
dia_semana                     0.0
numero_contatos_campanha       0.0
dias_desde_ultimo_contato      0.0
numero_contatos_anteriores     0.0
resultado_campanha_anterior    0.0
taxa_variacao_emprego          0.0
indice_preco_consumidor        0.0
indice_confianca_consumidor    0.0
taxa_euribor_3_meses           0.0
numero_empregados              0.0
conversao                      0.0
dtype: float64

In [46]:
df.shape

(41188, 19)

In [47]:
df.dtypes

idade                            int64
profissao                          str
estado_civil                       str
escolaridade                       str
emprestimo_habitacional            str
emprestimo_pessoal                 str
tipo_contato                       str
mes_contato                        str
dia_semana                         str
numero_contatos_campanha         int64
dias_desde_ultimo_contato        int64
numero_contatos_anteriores       int64
resultado_campanha_anterior        str
taxa_variacao_emprego          float64
indice_preco_consumidor        float64
indice_confianca_consumidor    float64
taxa_euribor_3_meses           float64
numero_empregados              float64
conversao                          str
dtype: object

In [48]:
df.columns

Index(['idade', 'profissao', 'estado_civil', 'escolaridade',
       'emprestimo_habitacional', 'emprestimo_pessoal', 'tipo_contato',
       'mes_contato', 'dia_semana', 'numero_contatos_campanha',
       'dias_desde_ultimo_contato', 'numero_contatos_anteriores',
       'resultado_campanha_anterior', 'taxa_variacao_emprego',
       'indice_preco_consumidor', 'indice_confianca_consumidor',
       'taxa_euribor_3_meses', 'numero_empregados', 'conversao'],
      dtype='str')

In [51]:
df["cliente_ja_contatado"] = (
    df["dias_desde_ultimo_contato"] != 999
).astype(int)

In [52]:
df['cliente_ja_contatado'].value_counts()

cliente_ja_contatado
0    39673
1     1515
Name: count, dtype: int64